### PR TITLE
Add CI framework

### PR DESCRIPTION
**Pull request by jeking3**
- travis with valgrind, cppcheck, ubsan, codecov, covscan (future)
  - appveyor with MSVC 2010 through 2017, cygwin 32/64, mingw 32/64
  - README, LICENSE, etc.

### CODE REVIEW

**Comment by jeking3** [comment]
The UBSAN failure looks real but it is in an example... we should still fix it.

**Comment by igaztanaga** [comment]
Thanks for pull request

**Comment by jeking3** [comment]
Sure, are you going to deal with the UBSAN failure separately?

**Comment by igaztanaga** [comment]
Looks that the latest changes have fixed the UBSAN report. Many thanks!

**Pull request merged**
